title: LitElement Documentation
toc:
  try: 
    title: Try LitElement
    desc: A quick tutorial with interactive code samples.
    url: /guide/try/
    toc: 
      create:
        title: 1. Create
        url: /guide/try/create
      import:
        title: 2. Import
        url: /guide/try/import
      properties:
        title: 3. Properties
        url: /guide/try/properties
      logic: 
        title: 4. Logic
        url: /guide/try/logic
      events:
        title: 5. Events
        url: /guide/try/events
      style: 
        title: 6. Style
        url: /guide/try/style
  templates: 
    title: Templates
    desc: Create and render LitElement templates. Use JavaScript expressions to add properties and logic.      
    url: /guide/templates/
    toc: 
      create: 
        title: Create a template
        desc: Define a template and specify where it should render.
        type: task
        url: /guide/templates/create
      expressions:
        title: Use properties and logic
        desc: Use JavaScript expressions to add properties, loops, and conditionals to your templates.
        type: task
        url: /guide/templates/expressions
      databinding:
        title: Bind data to a child element 
        desc: Bind to the text content, properties, attributes, and event handlers of a child element.
        type: task
        url: /guide/templates/databinding
      compose:
        title: Compose and nest templates 
        desc: Compose LitElement templates from other templates. 
        type: task
        url: /guide/templates/compose
      slots:
        title: Render light DOM children
        desc: Use slots to include light DOM children in shadow DOM templates.
        type: task
        url: /guide/templates/slots
      design:
        title: Template design concepts
        desc: Concepts for designing templates that render and update efficiently.
        type: concept
        url: /guide/templates/design
      syntax:
        title: Template syntax
        desc: A quick reference to LitElement template syntax.
        type: reference
        url: /guide/templates/syntax
  properties: 
    title: Properties
    desc: Declare and configure a component's properties and attributes.
    url: /guide/properties
    toc:
      declare: 
        title: Declare properties
        url: /guide/properties#declare
      init: 
        title: Initialize property values
        url: /guide/properties#init
      type:
        title: Configure a property type
        url: /guide/properties#type
      attribute:
        title: Configure observed attributes
        url: /guide/properties#attribute
      reflect:
        title: Configure reflection to attributes
        url: /guide/properties#reflect
      haschanged:
        title: Evaluate property changes
        url: /guide/properties#haschanged
  lifecycle: 
    title: Lifecycle
    desc: Specify when an element should update. Respond to updates, or wait for an update to complete.
    url: /guide/lifecycle/
    toc:
      about:
        title: About the element update lifecycle
        desc: Concepts for working with LitElement's asynchronous update lifecycle.
        type: concept
        url: /guide/lifecycle/about
      customize:
        title: Customize lifecycle behavior
        desc: Customize how and when an element should update, and perform additional tasks during any stage of the update lifecycle.
        type: task
        url: /guide/lifecycle/customize
      methods:
        title: Methods and Promises reference
        desc: A reference to the methods and Promises in the LitElement update lifecycle.
        type: reference
        url: /guide/lifecycle/methods
  tools:
    title: Tools
    desc: Tools for developing and deploying LitElement projects.
    url: /guide/tools/
    toc: 
      setup:
        title: Set up LitElement locally
        desc: Set up LitElement for the first time.
        url: /guide/tools/setup
      develop:
        title: Developer tools
        desc: Tools for developing and working locally with LitElement projects.
        url: /guide/tools/develop
      build: 
        title: Build for production
        desc: Get your project ready for deployment to the web.
        url: /guide/tools/build
      sample: 
        title: Sample project
        desc: Clone, serve, and build a sample LitElement project.
        url: /guide/tools/sample
